name: Build and Publish Docker Image

on:
  push:
    branches: [ master ]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    ## Checks out our project source code
    - uses: actions/checkout@v2
    
    ## Builds our docker image!
    - name: Build the Docker image
      run: make docker-build
      env:
        HUB: "ghcr.io/${{ github.actor }}"
        TAG: ${{ github.sha }}

    ## Login to github registry
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    ## Publish
    - name: Publish to Registry
      run: make docker-push
      env:
        HUB: "ghcr.io/${{ github.actor }}"
        TAG: ${{ github.sha }}